language: perl

install:
  - mkdir /tmp/pkgconf
  - git clone https://github.com/pkgconf/pkgconf.git /tmp/pkgconf/src
  - bash -c 'cd /tmp/pkgconf/src; ./autogen.sh && ./configure --prefix=/tmp/pkgconf --with-pic --disable-shared && make && make install'
  - env PKG_CONFIG_PATH=/tmp/pkgconf/lib/pkgconfig cpanm --installdeps -n -v .

perl:
  - "5.8"
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.22"
  - "5.24"
  
script:
  - env PKG_CONFIG_PATH=/tmp/pkgconf/lib/pkgconfig perl Makefile.PL
  - make
  - make test TEST_VERBOSE=1
