---
abstract: 'Perl bindings for libpkgconf'
author:
  - 'Graham Ollis <plicease@cpan.org>'
build_requires:
  ExtUtils::CBuilder: '0'
  Test::More: '0.94'
configure_requires:
  Module::Build: '0.38'
dynamic_config: 1
generated_by: 'Module::Build version 0.422, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: PkgConfig-LibPkgConf
provides:
  PkgConfig::LibPkgConf:
    file: lib/PkgConfig/LibPkgConf.pm
    version: '0.01'
  PkgConfig::LibPkgConf::Client:
    file: lib/PkgConfig/LibPkgConf/Client.pm
    version: '0.01'
  PkgConfig::LibPkgConf::FFI:
    file: lib/PkgConfig/LibPkgConf/FFI.pm
    version: '0.01'
  PkgConfig::LibPkgConf::FFI::Package:
    file: lib/PkgConfig/LibPkgConf/FFI.pm
  PkgConfig::LibPkgConf::Package:
    file: lib/PkgConfig/LibPkgConf/Package.pm
    version: '0.01'
  PkgConfig::LibPkgConf::Test:
    file: lib/PkgConfig/LibPkgConf/Test.pm
    version: '0.01'
  PkgConfig::LibPkgConf::Util:
    file: lib/PkgConfig/LibPkgConf/Util.pm
    version: '0.01'
  PkgConfig::LibPkgConf::XS:
    file: lib/PkgConfig/LibPkgConf/XS.pm
    version: '0.01'
requires:
  perl: '5.008001'
resources:
  IRC: irc://irc.perl.org/#native
  MailingList: https://groups.google.com/forum/#!forum/perl5-alien
  bugtracker: http://github.com/plicease/PkgConfig-LibPkgConf/issues
  license: http://dev.perl.org/licenses/
  repository: http://github.com/plicease/PkgConfig-LibPkgConf
version: '0.01'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
