#!/bin/sh -x

# this is intended for Debian only.
# I may update it later as needed

export MYTMP=`mktemp -d`/build
export MYPREFIX=$HOME/opt/pkgconf
export SYSTEM_LIBDIRS=`gcc -print-search-dirs | sed -n -e's/^libraries: =//p' | sed -e 's/:/\n/g' | xargs -n1 readlink -f | grep -v 'gcc\|/[0-9.]\+$$' | sort -u | tr '\n' : | sed 's/:$$//'`
export DEB_HOST_MULTIARCH=x86_64-linux-gnu

git clone https://github.com/pkgconf/pkgconf.git $MYTMP

cd $MYTMP

./autogen.sh

./configure \
  --prefix=$MYPREFIX \
  --mandir=$MYPREFIX/share/man \
  --infodir=$MYPREFIX/share/info \
  --enable-shared \
  --with-pic \
  --with-pkg-config-dir=$MYPREFIX/lib/pkgconfig:/usr/local/lib/$DEB_HOST_MULTIARCH/pkgconfig:/usr/local/lib/pkgconfig:/usr/local/share/pkgconfig:/usr/lib/$DEB_HOST_MULTIARCH/pkgconfig:/usr/lib/pkgconfig:/usr/share/pkgconfig \
  --with-system-libdir=$SYSTEM_LIBDIRS

make

rm -rf $MYPREFIX
make install

mkdir $MYPREFIX/dll
mv $MYPREFIX/lib/*.so* $MYPREFIX/dll

cd $HOME

rm -rf $MYTMP
